import type { Classroom, ScheduleItem, UpcomingItem } from "@/types/classroom";

export const CLASSROOMS: Classroom[] = [
  {
    id: "science-8a",
    name: "Grade 8 Science",
    section: "Section A",
    subject: "Science",
    theme: "from-emerald-500 to-teal-600",
    studentCount: 42,
    assignmentCount: 8,
    roomCode: "xk7m-p2nq",
    teacherName: "John Doe",
  },
  {
    id: "english-5b",
    name: "Grade 5 English",
    section: "Section B",
    subject: "English",
    theme: "from-violet-500 to-purple-600",
    studentCount: 38,
    assignmentCount: 5,
    roomCode: "ab3c-9k2l",
    teacherName: "John Doe",
  },
  {
    id: "math-10a",
    name: "Grade 10 Mathematics",
    section: "Section A",
    subject: "Mathematics",
    theme: "from-blue-500 to-indigo-600",
    studentCount: 35,
    assignmentCount: 12,
    roomCode: "mn4p-7x1z",
    teacherName: "John Doe",
  },
  {
    id: "physics-11",
    name: "Grade 11 Physics",
    section: "Section C",
    subject: "Physics",
    theme: "from-orange-500 to-amber-600",
    studentCount: 28,
    assignmentCount: 6,
    roomCode: "ph2w-5r8t",
    teacherName: "John Doe",
  },
  {
    id: "chemistry-9",
    name: "Grade 9 Chemistry",
    section: "Section A",
    subject: "Chemistry",
    theme: "from-rose-500 to-pink-600",
    studentCount: 40,
    assignmentCount: 4,
    roomCode: "ch9k-3m6n",
    teacherName: "John Doe",
  },
  {
    id: "history-7",
    name: "Grade 7 Social Studies",
    section: "Section B",
    subject: "History",
    theme: "from-cyan-500 to-sky-600",
    studentCount: 36,
    assignmentCount: 3,
    roomCode: "hs7b-1q4v",
    teacherName: "John Doe",
  },
];

export const TODAY_SCHEDULE: ScheduleItem[] = [
  {
    id: "s1",
    title: "Grade 8 Science – Electricity Unit",
    time: "08:00 AM",
    endTime: "09:30 AM",
    type: "class",
    location: "Room 204",
    classroomId: "science-8a",
  },
  {
    id: "s2",
    title: "Staff Meeting – Curriculum Review",
    time: "10:00 AM",
    endTime: "10:45 AM",
    type: "meeting",
    location: "Conference Hall",
  },
  {
    id: "s3",
    title: "Grade 5 English – Literature",
    time: "11:15 AM",
    endTime: "12:45 PM",
    type: "class",
    location: "Room 112",
    classroomId: "english-5b",
  },
  {
    id: "s4",
    title: "Lunch Break",
    time: "12:45 PM",
    endTime: "01:30 PM",
    type: "break",
  },
  {
    id: "s5",
    title: "Grade 10 Mathematics – Trigonometry",
    time: "01:30 PM",
    endTime: "03:00 PM",
    type: "class",
    location: "Room 301",
    classroomId: "math-10a",
  },
  {
    id: "s6",
    title: "Parent–Teacher Check-in (Virtual)",
    time: "03:30 PM",
    endTime: "04:00 PM",
    type: "meeting",
    location: "Google Meet",
  },
];

export const UPCOMING_ITEMS: UpcomingItem[] = [
  {
    id: "u1",
    title: "Quiz on Electricity",
    dueLabel: "Due tomorrow, 21 Jun",
    type: "assignment",
    classroomName: "Grade 8 Science",
    urgent: true,
  },
  {
    id: "u2",
    title: "Essay submission – Poetry unit",
    dueLabel: "Due in 3 days",
    type: "assignment",
    classroomName: "Grade 5 English",
  },
  {
    id: "u3",
    title: "Unit Test – Trigonometry",
    dueLabel: "Due Fri, 27 Jun",
    type: "exam",
    classroomName: "Grade 10 Mathematics",
  },
  {
    id: "u4",
    title: "Science Fair project review",
    dueLabel: "Due next Mon",
    type: "event",
    classroomName: "Grade 8 Science",
  },
  {
    id: "u5",
    title: "Lab report – Acids & Bases",
    dueLabel: "Due in 5 days",
    type: "assignment",
    classroomName: "Grade 9 Chemistry",
  },
];

export function getClassroomById(id: string): Classroom | undefined {
  return CLASSROOMS.find((c) => c.id === id);
}
